### ISSUE TITLE
file-demo 拍照，xs max照片旋转

### ISSUE THREAD

**Issue by biezhenyu** [lin-xin/blog#38]
就是使用当前blog里面这个demo，前端展示的照片是旋转的，后端拿到的也是旋转的，（前置拍摄）
![WechatIMG50](https://user-images.githubusercontent.com/23213442/80692675-83778680-8b04-11ea-808e-583c94e7660f.jpeg)

**Comment by biezhenyu** [comment]
![WechatIMG50](https://user-images.githubusercontent.com/23213442/80692700-8e321b80-8b04-11ea-83fb-02476b5cd8a6.jpeg)

**Comment by lin-xin** [comment]
该demo测过安卓手机还iPhone6s后摄，无xs max可测，无法帮你解决
